/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminVista;
import AppCliente.conexion.Client;
import AppCliente.vista.proyecto.Pedido;
import AppServidora.BaseDeDatos;
import AppServidora.codigoPlatillo;
import AppServidora.platillo;
import general.Peticion;
import general.TipoAccion;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sebastian
 */
public class adminMain extends javax.swing.JFrame {

    /**
     * Creates new form adminMain
     */
    public adminMain() {
        initComponents();
        //socket = new Client();
        c = new Cargador();
        platillos = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame_VerPlatillos = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlatillos = new javax.swing.JTable();
        btnFiltroTipos = new javax.swing.JButton();
        filtroTipos = new javax.swing.JSpinner();
        Frame_CrearPlatillo = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_Nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_Descripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spinner_tamanoPorcion = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinner_piezasXPorcion = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spinner_caloriasPorcion = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spinner_caloriasPieza = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spinner_precio = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        Button_agregar = new javax.swing.JButton();
        txtRespuesta = new javax.swing.JLabel();
        comboBox_tipos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        Frame_TOP10 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_tp10 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Frame_TOP5 = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_nunca = new javax.swing.JTextArea();
        Frame_Tabla = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nuncas = new javax.swing.JButton();

        Frame_VerPlatillos.setMinimumSize(new java.awt.Dimension(1102, 633));

        jButton2.setText("Crear Platillo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablePlatillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePlatillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePlatillosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePlatillos);

        btnFiltroTipos.setText("Filtrar");
        btnFiltroTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Frame_VerPlatillosLayout = new javax.swing.GroupLayout(Frame_VerPlatillos.getContentPane());
        Frame_VerPlatillos.getContentPane().setLayout(Frame_VerPlatillosLayout);
        Frame_VerPlatillosLayout.setHorizontalGroup(
            Frame_VerPlatillosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_VerPlatillosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Frame_VerPlatillosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_VerPlatillosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(Frame_VerPlatillosLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filtroTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltroTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        Frame_VerPlatillosLayout.setVerticalGroup(
            Frame_VerPlatillosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_VerPlatillosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Frame_VerPlatillosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Frame_VerPlatillosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFiltroTipos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(filtroTipos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        Frame_CrearPlatillo.setMinimumSize(new java.awt.Dimension(495, 703));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Crear Platillo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("TIPO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Descripción: ");

        text_Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_DescripcionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Calorías en una porción:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("kcal");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tamaño de porción:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Piezas por porción:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("gramos");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Precio:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("kcal");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Calorías en una pieza:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("colones");

        Button_agregar.setText("Agregar");
        Button_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_agregarActionPerformed(evt);
            }
        });

        txtRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout Frame_CrearPlatilloLayout = new javax.swing.GroupLayout(Frame_CrearPlatillo.getContentPane());
        Frame_CrearPlatillo.getContentPane().setLayout(Frame_CrearPlatilloLayout);
        Frame_CrearPlatilloLayout.setHorizontalGroup(
            Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(comboBox_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                            .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9)
                                .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(48, 48, 48)
                                    .addComponent(spinner_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13))
                            .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinner_piezasXPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                            .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(spinner_tamanoPorcion, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(spinner_caloriasPorcion)
                                                .addComponent(spinner_caloriasPieza))
                                            .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel12)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_CrearPlatilloLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10))))))
                                .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel14))))
                        .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(text_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                            .addComponent(Button_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(106, 106, 106))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        Frame_CrearPlatilloLayout.setVerticalGroup(
            Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(comboBox_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_CrearPlatilloLayout.createSequentialGroup()
                        .addComponent(text_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_tamanoPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinner_piezasXPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinner_caloriasPorcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_caloriasPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Frame_CrearPlatilloLayout.createSequentialGroup()
                        .addComponent(spinner_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(Frame_CrearPlatilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel14)))
                .addGap(54, 54, 54)
                .addComponent(Button_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("jLabel3");

        Frame_TOP10.setMinimumSize(new java.awt.Dimension(686, 779));

        text_tp10.setColumns(20);
        text_tp10.setRows(5);
        text_tp10.setMinimumSize(new java.awt.Dimension(164, 74));
        jScrollPane2.setViewportView(text_tp10);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("TOP 10");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Platillos más pedidos");

        javax.swing.GroupLayout Frame_TOP10Layout = new javax.swing.GroupLayout(Frame_TOP10.getContentPane());
        Frame_TOP10.getContentPane().setLayout(Frame_TOP10Layout);
        Frame_TOP10Layout.setHorizontalGroup(
            Frame_TOP10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_TOP10Layout.createSequentialGroup()
                .addGroup(Frame_TOP10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_TOP10Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel15))
                    .addGroup(Frame_TOP10Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel16))
                    .addGroup(Frame_TOP10Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        Frame_TOP10Layout.setVerticalGroup(
            Frame_TOP10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_TOP10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Frame_TOP5.setMinimumSize(new java.awt.Dimension(615, 482));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Pedidos NUNCA Ordenados");

        text_nunca.setColumns(20);
        text_nunca.setRows(5);
        text_nunca.setMinimumSize(new java.awt.Dimension(164, 74));
        jScrollPane3.setViewportView(text_nunca);

        javax.swing.GroupLayout Frame_TOP5Layout = new javax.swing.GroupLayout(Frame_TOP5.getContentPane());
        Frame_TOP5.getContentPane().setLayout(Frame_TOP5Layout);
        Frame_TOP5Layout.setHorizontalGroup(
            Frame_TOP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_TOP5Layout.createSequentialGroup()
                .addGroup(Frame_TOP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_TOP5Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel17))
                    .addGroup(Frame_TOP5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel18))
                    .addGroup(Frame_TOP5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Frame_TOP5Layout.setVerticalGroup(
            Frame_TOP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_TOP5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Frame_Tabla.setMinimumSize(new java.awt.Dimension(625, 490));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Porcentaje de Pedidos");

        javax.swing.GroupLayout Frame_TablaLayout = new javax.swing.GroupLayout(Frame_Tabla.getContentPane());
        Frame_Tabla.getContentPane().setLayout(Frame_TablaLayout);
        Frame_TablaLayout.setHorizontalGroup(
            Frame_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_TablaLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel19)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        Frame_TablaLayout.setVerticalGroup(
            Frame_TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_TablaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(468, 212));

        jButton1.setText("Ver Platillos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("TOP 10");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Porcentajes");

        nuncas.setText("Nunca Pedidos");
        nuncas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuncasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuncas))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuncas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void actualizar(){
    }
    
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.filtroTipos.setModel(c.selectorTipos());
        Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
        Client socket2 = new Client(nuevaPeticion2); 
        platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
        
        
        
        this.tablePlatillos.setModel(c.cargarTablaPlatillos(platillos));
        
        Frame_VerPlatillos.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_DescripcionActionPerformed
    
    public int randomCheck(){
        Random random = new Random();   
        // Generates random integers 0 to 49  
        int x = random.nextInt(900) + 100;
        for(int i =0; i < platillos.size();i++){
            if(platillos.get(i).getCodeNum() == x){
                return 0;
            }
        }
        return x;
    }
    
    private void Button_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_agregarActionPerformed
        // TODO add your handling code here:
        platillo p = new platillo();
        String nombre = this.text_Nombre.getText();
        p.setNombre(nombre);
        
        int precio = (int)this.spinner_precio.getValue();
        p.setPrecio(precio);
        
        String descripcion = this.text_Descripcion.getText();
        p.setDescripcion(descripcion);
        
        int caloriasXpiexa = (int)spinner_caloriasPieza.getValue();
        p.setCaloriasUnaPieza(caloriasXpiexa);
        
        int caloriasXporcion = (int)spinner_caloriasPorcion.getValue();
        p.setCaloriasUnaPorcion(caloriasXporcion);
        
        codigoPlatillo tipo = (codigoPlatillo)comboBox_tipos.getValue();
        p.setCodigoPlatillo(tipo);
        
        int piezasXporcion = (int)spinner_piezasXPorcion.getValue();
        p.setPiezasXPorcion(piezasXporcion);
        
        int tamano = (int)spinner_tamanoPorcion.getValue();
        p.setPorcionT(tamano);
        
        Peticion nuevaPeticion = new Peticion(TipoAccion.AGREGAR,p);
        Client socket = new Client(nuevaPeticion);
        this.txtRespuesta.setText((String) socket.getRespuestaServer());
        
        Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
        Client socket2 = new Client(nuevaPeticion2);
        
        ArrayList<platillo> platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
        
        //this.tablePlatillos.setModel(c.cargarTablaPlatillos(platillos));
        this.tablePlatillos.setModel(c.cargarTablaPlatillos(platillos));
        tablePlatillos.setDefaultRenderer(Object.class, new TablaRenderer());
        for (int i = 0; i < tablePlatillos.getRowCount(); i++){
            //tblPlatillos.setValueAt(c.crearBoton("eliminar"), i, 9);
            //tablePlatillos.setValueAt(c.crearBoton("Visibilidad"), i, 8);
           
        }
    }//GEN-LAST:event_Button_agregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        this.comboBox_tipos.setModel(c.selectorTipos());
        this.Frame_CrearPlatillo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFiltroTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroTiposActionPerformed
        // TODO add your handling code here:
     
        Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
        Client socket2 = new Client(nuevaPeticion2); 
        ArrayList<platillo> platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
        
        
        codigoPlatillo codigo = (codigoPlatillo)this.filtroTipos.getValue();
        this.tablePlatillos.setModel(c.cargarTablaPlatillosClienteFiltro(platillos,codigo));
        tablePlatillos.setDefaultRenderer(Object.class, new TablaRenderer());
        for (int i = 0; i < tablePlatillos.getRowCount(); i++){
            //tblPlatillos.setValueAt(c.crearBoton("eliminar"), i, 9);
            //tablePlatillos.setValueAt(c.crearBoton("Visibilidad"), i, 8);
           
        }
        //Frame_MenuClients.setVisible(true);
    }//GEN-LAST:event_btnFiltroTiposActionPerformed

    private void tablePlatillosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePlatillosMouseClicked
        // TODO add your handling code here:
        int column = this.tablePlatillos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tablePlatillos.getRowHeight();
        
        if(row < tablePlatillos.getRowCount() && row >= 0 && column < tablePlatillos.getColumnCount() && column >= 0){
            Object value = tablePlatillos.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
//                JButton boton = (JButton) value;
//                Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
//                Client socket2 = new Client(nuevaPeticion2); 
//                ArrayList<platillo> platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
               
                
                if (platillos.get(row).getVisible()){
                    platillos.get(row).setVisible(false);
                }
                else{
                    platillos.get(row).setVisible(true);
                }
                Peticion nuevaPeticion3 = new Peticion(TipoAccion.CONSULTAR_PRODUCTO,platillos);
                Client socket3 = new Client(nuevaPeticion3);
                
            }
        }
    }//GEN-LAST:event_tablePlatillosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
        Client socket2 = new Client(nuevaPeticion2); 
        platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
        
        
        Peticion p = new Peticion(TipoAccion.CONSULTA,null);
        Client cl = new Client(p);
        ArrayList<Pedido> ordenes = (ArrayList<Pedido>) cl.getRespuestaServer();
        ArrayList<platillo> menuFinal = c.cargarTodo(ordenes, platillos);
        text_tp10.setText(c.getTop10(menuFinal));
        Frame_TOP10.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nuncasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuncasActionPerformed
        Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
        Client socket2 = new Client(nuevaPeticion2); 
        platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
        
        Peticion p = new Peticion(TipoAccion.CONSULTA,null);
        Client cl = new Client(p);
        ArrayList<Pedido> ordenes = (ArrayList<Pedido>) cl.getRespuestaServer();
        ArrayList<platillo> menuFinal = c.cargarTodo(ordenes, platillos);
        text_nunca.setText(c.nunca(menuFinal));
        Frame_TOP5.setVisible(true);
    }//GEN-LAST:event_nuncasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMain().setVisible(true);
            }
        });
    }
    private ArrayList<platillo> platillos;
    private Cargador c;
    //private Client socket;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_agregar;
    private javax.swing.JFrame Frame_CrearPlatillo;
    private javax.swing.JFrame Frame_TOP10;
    private javax.swing.JFrame Frame_TOP5;
    private javax.swing.JFrame Frame_Tabla;
    private javax.swing.JFrame Frame_VerPlatillos;
    private javax.swing.JButton btnFiltroTipos;
    private javax.swing.JSpinner comboBox_tipos;
    private javax.swing.JSpinner filtroTipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nuncas;
    private javax.swing.JSpinner spinner_caloriasPieza;
    private javax.swing.JSpinner spinner_caloriasPorcion;
    private javax.swing.JSpinner spinner_piezasXPorcion;
    private javax.swing.JSpinner spinner_precio;
    private javax.swing.JSpinner spinner_tamanoPorcion;
    private javax.swing.JTable tablePlatillos;
    private javax.swing.JTextField text_Descripcion;
    private javax.swing.JTextField text_Nombre;
    private javax.swing.JTextArea text_nunca;
    private javax.swing.JTextArea text_tp10;
    private javax.swing.JLabel txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
