/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppCliente.vista.proyecto;

import AdminVista.Cargador;
import AdminVista.TablaRenderer;
import AppCliente.conexion.Client;
import AppServidora.codigoPlatillo;
import AppServidora.platillo;
import general.Peticion;
import general.TipoAccion;
import static java.awt.SystemColor.control;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Sebastian
 */
public class clientMain extends javax.swing.JFrame {

    /**
     * Creates new form clientMain
     */
    public clientMain() {
        initComponents();
        platillos = new ArrayList();
        base = new BaseCliente();
        c = new Cargador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame_MenuClients = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlatillos = new javax.swing.JTable();
        btnFiltroTipos = new javax.swing.JButton();
        filtroTipos = new javax.swing.JSpinner();
        Frame_Carrito = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        button_comprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCarrito = new javax.swing.JTable();
        comboBox_TipoOrden = new javax.swing.JSpinner();
        Frame_Factura = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblRespuestaPedido = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_factura = new javax.swing.JTextArea();
        Frame_recoger = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        continuar_recoger = new javax.swing.JButton();
        Frame_express = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_numeroExpress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        button_expressContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button_verMenuCLients = new javax.swing.JButton();
        button_VerCarrito = new javax.swing.JButton();

        Frame_MenuClients.setMinimumSize(new java.awt.Dimension(895, 472));

        tblPlatillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPlatillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlatillosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPlatillos);

        btnFiltroTipos.setText("Filtrar");
        btnFiltroTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroTiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Frame_MenuClientsLayout = new javax.swing.GroupLayout(Frame_MenuClients.getContentPane());
        Frame_MenuClients.getContentPane().setLayout(Frame_MenuClientsLayout);
        Frame_MenuClientsLayout.setHorizontalGroup(
            Frame_MenuClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_MenuClientsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Frame_MenuClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_MenuClientsLayout.createSequentialGroup()
                        .addComponent(filtroTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltroTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        Frame_MenuClientsLayout.setVerticalGroup(
            Frame_MenuClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_MenuClientsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Frame_MenuClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltroTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTipos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        Frame_Carrito.setMinimumSize(new java.awt.Dimension(920, 724));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tipo de pedido:");

        button_comprar.setText("Realizar Pedido");
        button_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_comprarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nombre del cliente:");

        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });

        tableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarritoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCarrito);

        javax.swing.GroupLayout Frame_CarritoLayout = new javax.swing.GroupLayout(Frame_Carrito.getContentPane());
        Frame_Carrito.getContentPane().setLayout(Frame_CarritoLayout);
        Frame_CarritoLayout.setHorizontalGroup(
            Frame_CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_CarritoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_CarritoLayout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addGroup(Frame_CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Frame_CarritoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Frame_CarritoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox_TipoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(33, 33, 33)
                .addComponent(button_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        Frame_CarritoLayout.setVerticalGroup(
            Frame_CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_CarritoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(Frame_CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_nombre)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Frame_CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_comprar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_CarritoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(10, 10, 10)))
                    .addComponent(comboBox_TipoOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        Frame_Factura.setMinimumSize(new java.awt.Dimension(534, 690));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Gracias por comprar con nosotros!");

        lblRespuestaPedido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        text_factura.setColumns(20);
        text_factura.setRows(5);
        jScrollPane3.setViewportView(text_factura);

        javax.swing.GroupLayout Frame_FacturaLayout = new javax.swing.GroupLayout(Frame_Factura.getContentPane());
        Frame_Factura.getContentPane().setLayout(Frame_FacturaLayout);
        Frame_FacturaLayout.setHorizontalGroup(
            Frame_FacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_FacturaLayout.createSequentialGroup()
                .addGroup(Frame_FacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_FacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRespuestaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Frame_FacturaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3))
                    .addGroup(Frame_FacturaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        Frame_FacturaLayout.setVerticalGroup(
            Frame_FacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_FacturaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(Frame_FacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespuestaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Frame_recoger.setMinimumSize(new java.awt.Dimension(437, 256));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Pedido para recoger");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Número de teléfono:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Costo Adicional: 400₡");

        continuar_recoger.setText("Continuar");
        continuar_recoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar_recogerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Frame_recogerLayout = new javax.swing.GroupLayout(Frame_recoger.getContentPane());
        Frame_recoger.getContentPane().setLayout(Frame_recogerLayout);
        Frame_recogerLayout.setHorizontalGroup(
            Frame_recogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_recogerLayout.createSequentialGroup()
                .addGroup(Frame_recogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_recogerLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel5))
                    .addGroup(Frame_recogerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Frame_recogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(Frame_recogerLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Frame_recogerLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(continuar_recoger)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Frame_recogerLayout.setVerticalGroup(
            Frame_recogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_recogerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(64, 64, 64)
                .addGroup(Frame_recogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_numero))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(continuar_recoger)
                .addGap(19, 19, 19))
        );

        Frame_express.setMinimumSize(new java.awt.Dimension(581, 402));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Pedido Express");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Número de teléfono:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Dirección Exacta:");

        text_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Costo Adicional: 800₡");

        button_expressContinuar.setText("Continuar");
        button_expressContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_expressContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Frame_expressLayout = new javax.swing.GroupLayout(Frame_express.getContentPane());
        Frame_express.getContentPane().setLayout(Frame_expressLayout);
        Frame_expressLayout.setHorizontalGroup(
            Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_expressLayout.createSequentialGroup()
                .addGroup(Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame_expressLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel8))
                    .addGroup(Frame_expressLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Frame_expressLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(text_numeroExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_expressLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(17, 17, 17)
                                    .addComponent(text_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11))))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_expressLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_expressContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        Frame_expressLayout.setVerticalGroup(
            Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_expressLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addGroup(Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(text_numeroExpress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Frame_expressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(text_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_expressContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("BIENVENIDO!");

        button_verMenuCLients.setText("Ver Menu");
        button_verMenuCLients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_verMenuCLientsActionPerformed(evt);
            }
        });

        button_VerCarrito.setText("Ver Carrito");
        button_VerCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_VerCarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(button_verMenuCLients, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(button_VerCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_verMenuCLients, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_VerCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void button_verMenuCLientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_verMenuCLientsActionPerformed
        
        this.filtroTipos.setModel(c.selectorTipos());
        
        Peticion nuevaPeticion2 = new Peticion(TipoAccion.VER_PRODUCTOS,null);
        Client socket2 = new Client(nuevaPeticion2);
        
        this.platillos = (ArrayList<platillo>)socket2.getRespuestaServer();
        
        this.tblPlatillos.setModel(c.cargarTablaPlatillosVisibles(platillos));
        tblPlatillos.setDefaultRenderer(Object.class, new TablaRenderer());
        for (int i = 0; i < tblPlatillos.getRowCount(); i++){
            //tblPlatillos.setValueAt(c.crearBoton("eliminar"), i, 9);
            tblPlatillos.setValueAt(c.crearBoton("agregar"), i, 8);
           
        }
        
        Frame_MenuClients.setVisible(true);
        
    }//GEN-LAST:event_button_verMenuCLientsActionPerformed

    private void button_VerCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_VerCarritoActionPerformed
       
//        this.tableCarrito.setModel(c.cargarTablaPlatillosCarrito(base.getCarrito()));
//        tableCarrito.setDefaultRenderer(Object.class, new TablaRenderer());
//        for (int i = 0; i < tableCarrito.getRowCount(); i++){
//            //tblPlatillos.setValueAt(c.crearBoton("eliminar"), i, 9);
//            tableCarrito.setValueAt(c.crearBoton("eliminar"), i, 9);
//           
//        }
//        this.comboBox_TipoOrden.setModel(c.selectorEnvio());
        actualizarCarrito();
        Frame_Carrito.setVisible(true);
    }//GEN-LAST:event_button_VerCarritoActionPerformed
    private void actualizarCarrito(){
        this.tableCarrito.setModel(c.cargarTablaPlatillosCarrito(base.getCarrito()));
        tableCarrito.setDefaultRenderer(Object.class, new TablaRenderer());
        for (int i = 0; i < tableCarrito.getRowCount(); i++){
            //tblPlatillos.setValueAt(c.crearBoton("eliminar"), i, 9);
            tableCarrito.setValueAt(c.crearBoton("eliminar"), i, 9);
           
        }
        this.comboBox_TipoOrden.setModel(c.selectorEnvio());
    }
    
    private String getFactura(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();  
        String c = Integer.toString(base.cantidad+1);
        int total = 0;
        
        String res = "\t\tOrden #" + c + "\n\nFecha: " + dtf.format(now) + "\n\nCliente: "+ text_nombre.getText()+
                "\n\n\t\tPedido:" + "\n\n";
        for(int i = 0;i < base.getCarrito().size();i++){
            total += (base.getCarrito().get(i).getPrecio() * base.getCarrito().get(i).getVentas());
            res+= "" + base.getCarrito().get(i).getVentas() +"\t"+ base.getCarrito().get(i).getCodeID()+"-" + base.getCarrito().get(i).getCodeNum()+ "\t"+base.getCarrito().get(i).getNombre()+ "\t" +
                    "\tPrecio C/U  " + platillos.get(i).getPrecio() + "\n";
        }
        if(comboBox_TipoOrden.getValue().equals("Express")){
            res += "\nNumero de teléfono: " + text_numeroExpress.getText() + "\n";
            total += 800;
            res += "\nCosto envío 800₡\n\n";
        } else if(comboBox_TipoOrden.getValue().equals("Recoger")){
            res += "\n Numero de teléfono: " + text_numero.getText() + "\n";
            total += 400;
            res += "\nCosto envío 400₡\n\n";
        } else if(comboBox_TipoOrden.getValue().equals("Sitio")){
            res += "\nSin costo de envío\n\n";
        }
        res += "Total a pagar: " + total;
        return res;
    }
    
    private void button_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_comprarActionPerformed
        if(base.getCarrito().size() == 0){
            infoBox("La orden esta vacia!", "ERROR USUARIO");
        } else{
            if(text_nombre.getText().equals("")){
                infoBox("La orden no tiene un nombre asignado!", "ERROR USUARIO");
            }else{
                if ((String)comboBox_TipoOrden.getValue() == "Express"){
                    Frame_express.setVisible(true);
                }
                else if ((String)comboBox_TipoOrden.getValue() == "Recoger"){
                    Frame_recoger.setVisible(true);
                }
                else{
                    this.Frame_Factura.setVisible(true);
                    text_factura.setText(getFactura());
                }
        }
    }
        
        
    }//GEN-LAST:event_button_comprarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Frame_Factura.setVisible(false);
        Frame_Carrito.setVisible(false);
        Frame_MenuClients.setVisible(false);
        
        infoBox("Disfrute su pedido\n Estará listo pronto!", "Provecho!");
        String modo = (String)this.comboBox_TipoOrden.getValue();
        Peticion p = new Peticion(TipoAccion.AGREGAR_CARRITO,base.enviarPedido(modo));
        Client conexion = new Client(p);
        
        base.limpiarCarrito();
//        this.lblRespuestaPedido.setText((String)conexion.getRespuestaServer());
        
//        new clientMain().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void continuar_recogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar_recogerActionPerformed
            if(text_numero.getText().equals("")){
                infoBox("La orden no tiene un numero asignado!", "ERROR USUARIO");
            }else{
                Frame_recoger.setVisible(false);
                text_factura.setText(getFactura());
                Frame_Factura.setVisible(true);
            }
            
    }//GEN-LAST:event_continuar_recogerActionPerformed

    private void text_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccionActionPerformed

    private void button_expressContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_expressContinuarActionPerformed
        if(text_numeroExpress.getText().equals("") || text_direccion.getText().equals("")){
            infoBox("El número o la dirección estan incorrectos", "ERROR USUARIO");
        }else{
            Frame_recoger.setVisible(false);
            Frame_express.setVisible(false);
            text_factura.setText(getFactura());
            Frame_Factura.setVisible(true);
        }
    }//GEN-LAST:event_button_expressContinuarActionPerformed

    private void btnFiltroTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroTiposActionPerformed
        // TODO add your handling code here:
        codigoPlatillo codigo = (codigoPlatillo)this.filtroTipos.getValue();
        this.tblPlatillos.setModel(c.cargarTablaPlatillosClienteFiltro(platillos,codigo));
        tblPlatillos.setDefaultRenderer(Object.class, new TablaRenderer());
        for (int i = 0; i < tblPlatillos.getRowCount(); i++){
            //tblPlatillos.setValueAt(c.crearBoton("eliminar"), i, 9);
            tblPlatillos.setValueAt(c.crearBoton("agregar"), i, 8);
           
        }
        
        //Frame_MenuClients.setVisible(true);
    }//GEN-LAST:event_btnFiltroTiposActionPerformed

    private void tblPlatillosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlatillosMouseClicked
        // TODO add your handling code here:
        int column = this.tblPlatillos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblPlatillos.getRowHeight();
        
        if(row < tblPlatillos.getRowCount() && row >= 0 && column < tblPlatillos.getColumnCount() && column >= 0){
            Object value = tblPlatillos.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
                
                
                platillo p = platillos.get(row);
                base.agregarCarrito(p);
                
                
            }
        }
    }//GEN-LAST:event_tblPlatillosMouseClicked

    private void tableCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarritoMouseClicked
        // TODO add your handling code here:
        int column = this.tableCarrito.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tableCarrito.getRowHeight();
        
        if(row < tableCarrito.getRowCount() && row >= 0 && column < tableCarrito.getColumnCount() && column >= 0){
            Object value = tableCarrito.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
  
                platillo p = platillos.get(row);
                base.eliminar(p.getNombre());
                actualizarCarrito();
  
            }
        }
    }//GEN-LAST:event_tableCarritoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientMain().setVisible(true);
            }
        });
    }
    ArrayList<platillo> platillos;
    BaseCliente base;
    Cargador c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Frame_Carrito;
    private javax.swing.JFrame Frame_Factura;
    private javax.swing.JFrame Frame_MenuClients;
    private javax.swing.JFrame Frame_express;
    private javax.swing.JFrame Frame_recoger;
    private javax.swing.JButton btnFiltroTipos;
    private javax.swing.JButton button_VerCarrito;
    private javax.swing.JButton button_comprar;
    private javax.swing.JButton button_expressContinuar;
    private javax.swing.JButton button_verMenuCLients;
    private javax.swing.JSpinner comboBox_TipoOrden;
    private javax.swing.JButton continuar_recoger;
    private javax.swing.JSpinner filtroTipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblRespuestaPedido;
    private javax.swing.JTable tableCarrito;
    private javax.swing.JTable tblPlatillos;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextArea text_factura;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_numero;
    private javax.swing.JTextField text_numeroExpress;
    // End of variables declaration//GEN-END:variables
}
